---
- name: Show Manager IP from worker
  debug:
    msg: "Manager IP is: {{ hostvars['manager_node']['manager_ip'] }}"

- name: Join Swarm cluster using manager's join command
  shell: "{{ hostvars['manager_node']['join_command'] }}"


